# Generated by Django 2.2 on 2021-05-21 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_auto_20210519_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogActualHourEdit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initial_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('change_delta', models.DecimalField(decimal_places=2, max_digits=5)),
                ('final_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_changed_by', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'verbose_name_plural': 'Log actual hour edits',
            },
        ),
    ]
